<?xml version="1.0" encoding="utf-8"?><Database Name="MainDatabase" Class="MainDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\MainDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MainDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.USER_" Member="USER_s">
    <Type Name="USER_">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Contacts" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WhatsApp" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="University" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ResName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Addressline1" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Addressline2" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Addressline3" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PassPhrase" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>